//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppFacadeWS.RecuperarCatalogoBB2 {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobancolombia.com/intf/ServiciosAdministrativos/ServiciosdeInformacionD" +
        "ocumental/RecuperarCatalogo_BB2/V1.0")]
    public partial class SystemException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private GenericException genericExceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public GenericException genericException {
            get {
                return this.genericExceptionField;
            }
            set {
                this.genericExceptionField = value;
                this.RaisePropertyChanged("genericException");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobancolombia.com/ents/common/GenericException/V2.0")]
    public partial class GenericException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobancolombia.com/intf/ServiciosAdministrativos/ServiciosdeInformacionD" +
        "ocumental/RecuperarCatalogo_BB2/V1.0")]
    public partial class documents : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string conditionFormField;
        
        private string documentSubTypeField;
        
        private string documentTypeField;
        
        private string documentTypeNameField;
        
        private int expiryDaysField;
        
        private bool expiryDaysFieldSpecified;
        
        private string obligatoryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string conditionForm {
            get {
                return this.conditionFormField;
            }
            set {
                this.conditionFormField = value;
                this.RaisePropertyChanged("conditionForm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string documentSubType {
            get {
                return this.documentSubTypeField;
            }
            set {
                this.documentSubTypeField = value;
                this.RaisePropertyChanged("documentSubType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string documentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
                this.RaisePropertyChanged("documentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string documentTypeName {
            get {
                return this.documentTypeNameField;
            }
            set {
                this.documentTypeNameField = value;
                this.RaisePropertyChanged("documentTypeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int expiryDays {
            get {
                return this.expiryDaysField;
            }
            set {
                this.expiryDaysField = value;
                this.RaisePropertyChanged("expiryDays");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expiryDaysSpecified {
            get {
                return this.expiryDaysFieldSpecified;
            }
            set {
                this.expiryDaysFieldSpecified = value;
                this.RaisePropertyChanged("expiryDaysSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string obligatory {
            get {
                return this.obligatoryField;
            }
            set {
                this.obligatoryField = value;
                this.RaisePropertyChanged("obligatory");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobancolombia.com/intf/ServiciosAdministrativos/ServiciosdeInformacionD" +
        "ocumental/RecuperarCatalogo_BB2/V1.0")]
    public partial class RecuperarCatalogoPorProductoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private documents[] returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public documents[] @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobancolombia.com/intf/ServiciosAdministrativos/ServiciosdeInformacionD" +
        "ocumental/RecuperarCatalogo_BB2/V1.0")]
    public partial class attributes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobancolombia.com/intf/ServiciosAdministrativos/ServiciosdeInformacionD" +
        "ocumental/RecuperarCatalogo_BB2/V1.0")]
    public partial class productRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private attributes[] attributesField;
        
        private string branchCodeField;
        
        private string productCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attributes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public attributes[] attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
                this.RaisePropertyChanged("attributes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string branchCode {
            get {
                return this.branchCodeField;
            }
            set {
                this.branchCodeField = value;
                this.RaisePropertyChanged("branchCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string productCode {
            get {
                return this.productCodeField;
            }
            set {
                this.productCodeField = value;
                this.RaisePropertyChanged("productCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobancolombia.com/intf/ServiciosAdministrativos/ServiciosdeInformacionD" +
        "ocumental/RecuperarCatalogo_BB2/V1.0")]
    public partial class RecuperarCatalogoPorProducto : object, System.ComponentModel.INotifyPropertyChanged {
        
        private productRequest arg0Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public productRequest arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
                this.RaisePropertyChanged("arg0");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobancolombia.com/intf/ServiciosAdministrativos/ServiciosdeInformacionD" +
        "ocumental/RecuperarCatalogo_BB2/V1.0")]
    public partial class ParametroNoEncontradoBusinessException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private GenericException genericExceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public GenericException genericException {
            get {
                return this.genericExceptionField;
            }
            set {
                this.genericExceptionField = value;
                this.RaisePropertyChanged("genericException");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobancolombia.com/intf/ServiciosAdministrativos/ServiciosdeInformacionD" +
        "ocumental/RecuperarCatalogo_BB2/V1.0")]
    public partial class ValorInvalidoEnParametroDependienteBusinessException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private GenericException genericExceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public GenericException genericException {
            get {
                return this.genericExceptionField;
            }
            set {
                this.genericExceptionField = value;
                this.RaisePropertyChanged("genericException");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://grupobancolombia.com/intf/ServiciosAdministrativos/ServiciosdeInformacionD" +
        "ocumental/RecuperarCatalogo_BB2/V1.0", ConfigurationName="RecuperarCatalogoBB2.RecuperarCatalogo_BB2")]
    public interface RecuperarCatalogo_BB2 {
        
        // CODEGEN: Generating message contract since the operation recuperarCatalogoPorProducto is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://grupobancolombia.com/intf/ServiciosAdministrativos/ServiciosdeInformacionD" +
            "ocumental/RecuperarCatalogo_BB2/V1.0/recuperarCatalogoPorProducto", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AppFacadeWS.RecuperarCatalogoBB2.SystemException), Action="http://grupobancolombia.com/intf/ServiciosAdministrativos/ServiciosdeInformacionD" +
            "ocumental/RecuperarCatalogo_BB2/V1.0/recuperarCatalogoPorProducto", Name="systemException")]
        [System.ServiceModel.FaultContractAttribute(typeof(AppFacadeWS.RecuperarCatalogoBB2.ParametroNoEncontradoBusinessException), Action="http://grupobancolombia.com/intf/ServiciosAdministrativos/ServiciosdeInformacionD" +
            "ocumental/RecuperarCatalogo_BB2/V1.0/recuperarCatalogoPorProducto", Name="parametroNoEncontradoBusinessException")]
        [System.ServiceModel.FaultContractAttribute(typeof(AppFacadeWS.RecuperarCatalogoBB2.ValorInvalidoEnParametroDependienteBusinessException), Action="http://grupobancolombia.com/intf/ServiciosAdministrativos/ServiciosdeInformacionD" +
            "ocumental/RecuperarCatalogo_BB2/V1.0/recuperarCatalogoPorProducto", Name="valorInvalidoEnParametroDependienteBusinessException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AppFacadeWS.RecuperarCatalogoBB2.recuperarCatalogoPorProductoResponse1 recuperarCatalogoPorProducto(AppFacadeWS.RecuperarCatalogoBB2.recuperarCatalogoPorProductoRequest request);
        
        // CODEGEN: Generating message contract since the operation recuperarCatalogoPorProceso is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://grupobancolombia.com/intf/ServiciosAdministrativos/ServiciosdeInformacionD" +
            "ocumental/RecuperarCatalogo_BB2/V1.0/recuperarCatalogoPorProceso", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AppFacadeWS.RecuperarCatalogoBB2.SystemException), Action="http://grupobancolombia.com/intf/ServiciosAdministrativos/ServiciosdeInformacionD" +
            "ocumental/RecuperarCatalogo_BB2/V1.0/recuperarCatalogoPorProceso", Name="systemException")]
        [System.ServiceModel.FaultContractAttribute(typeof(AppFacadeWS.RecuperarCatalogoBB2.ParametroNoEncontradoBusinessException), Action="http://grupobancolombia.com/intf/ServiciosAdministrativos/ServiciosdeInformacionD" +
            "ocumental/RecuperarCatalogo_BB2/V1.0/recuperarCatalogoPorProceso", Name="parametroNoEncontradoBusinessException")]
        [System.ServiceModel.FaultContractAttribute(typeof(AppFacadeWS.RecuperarCatalogoBB2.ValorInvalidoEnParametroDependienteBusinessException), Action="http://grupobancolombia.com/intf/ServiciosAdministrativos/ServiciosdeInformacionD" +
            "ocumental/RecuperarCatalogo_BB2/V1.0/recuperarCatalogoPorProceso", Name="valorInvalidoEnParametroDependienteBusinessException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AppFacadeWS.RecuperarCatalogoBB2.recuperarCatalogoPorProcesoResponse1 recuperarCatalogoPorProceso(AppFacadeWS.RecuperarCatalogoBB2.recuperarCatalogoPorProcesoRequest request);
        
        // CODEGEN: Generating message contract since the operation recuperarCatalogoPorCliente is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://grupobancolombia.com/intf/ServiciosAdministrativos/ServiciosdeInformacionD" +
            "ocumental/RecuperarCatalogo_BB2/V1.0/recuperarCatalogoPorCliente", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AppFacadeWS.RecuperarCatalogoBB2.SystemException), Action="http://grupobancolombia.com/intf/ServiciosAdministrativos/ServiciosdeInformacionD" +
            "ocumental/RecuperarCatalogo_BB2/V1.0/recuperarCatalogoPorCliente", Name="systemException")]
        [System.ServiceModel.FaultContractAttribute(typeof(AppFacadeWS.RecuperarCatalogoBB2.ParametroNoEncontradoBusinessException), Action="http://grupobancolombia.com/intf/ServiciosAdministrativos/ServiciosdeInformacionD" +
            "ocumental/RecuperarCatalogo_BB2/V1.0/recuperarCatalogoPorCliente", Name="parametroNoEncontradoBusinessException")]
        [System.ServiceModel.FaultContractAttribute(typeof(AppFacadeWS.RecuperarCatalogoBB2.ValorInvalidoEnParametroDependienteBusinessException), Action="http://grupobancolombia.com/intf/ServiciosAdministrativos/ServiciosdeInformacionD" +
            "ocumental/RecuperarCatalogo_BB2/V1.0/recuperarCatalogoPorCliente", Name="valorInvalidoEnParametroDependienteBusinessException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AppFacadeWS.RecuperarCatalogoBB2.recuperarCatalogoPorClienteResponse1 recuperarCatalogoPorCliente(AppFacadeWS.RecuperarCatalogoBB2.recuperarCatalogoPorClienteRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobancolombia.com/ents/SOI/MessageFormat/V2.1")]
    public partial class RequestHeader : Header {
        
        private UsernameToken userIdField;
        
        private Destination destinationField;
        
        private string[] classificationsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public UsernameToken userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("userId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Destination destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
                this.RaisePropertyChanged("destination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("classification", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI", IsNullable=false)]
        public string[] classifications {
            get {
                return this.classificationsField;
            }
            set {
                this.classificationsField = value;
                this.RaisePropertyChanged("classifications");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobancolombia.com/ents/SOI/CoreExtensions/V2.1")]
    public partial class UsernameToken : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private object userTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("userName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public object userToken {
            get {
                return this.userTokenField;
            }
            set {
                this.userTokenField = value;
                this.RaisePropertyChanged("userToken");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobancolombia.com/ents/SOI/CoreExtensions/V2.1")]
    public partial class Destination : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string namespaceField;
        
        private string operationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI", Order=1)]
        public string @namespace {
            get {
                return this.namespaceField;
            }
            set {
                this.namespaceField = value;
                this.RaisePropertyChanged("namespace");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
                this.RaisePropertyChanged("operation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResponseHeader))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RequestHeader))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobancolombia.com/ents/SOI/MessageFormat/V2.1")]
    public abstract partial class Header : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string systemIdField;
        
        private string messageIdField;
        
        private System.DateTime timestampField;
        
        private bool timestampFieldSpecified;
        
        private Property[] messageContextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string systemId {
            get {
                return this.systemIdField;
            }
            set {
                this.systemIdField = value;
                this.RaisePropertyChanged("systemId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string messageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
                this.RaisePropertyChanged("messageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
                this.RaisePropertyChanged("timestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timestampSpecified {
            get {
                return this.timestampFieldSpecified;
            }
            set {
                this.timestampFieldSpecified = value;
                this.RaisePropertyChanged("timestampSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Property[] messageContext {
            get {
                return this.messageContextField;
            }
            set {
                this.messageContextField = value;
                this.RaisePropertyChanged("messageContext");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobancolombia.com/ents/SOI/CoreExtensions/V2.1")]
    public partial class Property : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobancolombia.com/ents/SOI/MessageFormat/V2.1")]
    public partial class ResponseHeader : Header {
        
        private ResponseStatus responseStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResponseStatus responseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
                this.RaisePropertyChanged("responseStatus");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobancolombia.com/ents/SOI/CoreExtensions/V2.1")]
    public partial class ResponseStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private StatusCode statusCodeField;
        
        public ResponseStatus() {
            this.statusCodeField = StatusCode.Success;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public StatusCode statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("statusCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobancolombia.com/ents/SOI/CoreExtensions/V2.1")]
    public enum StatusCode {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        BusinessException,
        
        /// <remarks/>
        ProviderException,
        
        /// <remarks/>
        SystemException,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class recuperarCatalogoPorProductoRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://grupobancolombia.com/ents/SOI/MessageFormat/V2.1")]
        public AppFacadeWS.RecuperarCatalogoBB2.RequestHeader requestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://grupobancolombia.com/intf/ServiciosAdministrativos/ServiciosdeInformacionD" +
            "ocumental/RecuperarCatalogo_BB2/V1.0", Order=0)]
        public AppFacadeWS.RecuperarCatalogoBB2.RecuperarCatalogoPorProducto recuperarCatalogoPorProducto;
        
        public recuperarCatalogoPorProductoRequest() {
        }
        
        public recuperarCatalogoPorProductoRequest(AppFacadeWS.RecuperarCatalogoBB2.RequestHeader requestHeader, AppFacadeWS.RecuperarCatalogoBB2.RecuperarCatalogoPorProducto recuperarCatalogoPorProducto) {
            this.requestHeader = requestHeader;
            this.recuperarCatalogoPorProducto = recuperarCatalogoPorProducto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class recuperarCatalogoPorProductoResponse1 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://grupobancolombia.com/ents/SOI/MessageFormat/V2.1")]
        public AppFacadeWS.RecuperarCatalogoBB2.ResponseHeader responseHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://grupobancolombia.com/intf/ServiciosAdministrativos/ServiciosdeInformacionD" +
            "ocumental/RecuperarCatalogo_BB2/V1.0", Order=0)]
        public AppFacadeWS.RecuperarCatalogoBB2.RecuperarCatalogoPorProductoResponse recuperarCatalogoPorProductoResponse;
        
        public recuperarCatalogoPorProductoResponse1() {
        }
        
        public recuperarCatalogoPorProductoResponse1(AppFacadeWS.RecuperarCatalogoBB2.ResponseHeader responseHeader, AppFacadeWS.RecuperarCatalogoBB2.RecuperarCatalogoPorProductoResponse recuperarCatalogoPorProductoResponse) {
            this.responseHeader = responseHeader;
            this.recuperarCatalogoPorProductoResponse = recuperarCatalogoPorProductoResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobancolombia.com/intf/ServiciosAdministrativos/ServiciosdeInformacionD" +
        "ocumental/RecuperarCatalogo_BB2/V1.0")]
    public partial class RecuperarCatalogoPorProceso : object, System.ComponentModel.INotifyPropertyChanged {
        
        private processRequest arg0Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public processRequest arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
                this.RaisePropertyChanged("arg0");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobancolombia.com/intf/ServiciosAdministrativos/ServiciosdeInformacionD" +
        "ocumental/RecuperarCatalogo_BB2/V1.0")]
    public partial class processRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private attributes[] attributesField;
        
        private string branchCodeField;
        
        private string processCodeField;
        
        private string subProcessCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attributes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public attributes[] attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
                this.RaisePropertyChanged("attributes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string branchCode {
            get {
                return this.branchCodeField;
            }
            set {
                this.branchCodeField = value;
                this.RaisePropertyChanged("branchCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string processCode {
            get {
                return this.processCodeField;
            }
            set {
                this.processCodeField = value;
                this.RaisePropertyChanged("processCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string subProcessCode {
            get {
                return this.subProcessCodeField;
            }
            set {
                this.subProcessCodeField = value;
                this.RaisePropertyChanged("subProcessCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobancolombia.com/intf/ServiciosAdministrativos/ServiciosdeInformacionD" +
        "ocumental/RecuperarCatalogo_BB2/V1.0")]
    public partial class RecuperarCatalogoPorProcesoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private documents[] returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public documents[] @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class recuperarCatalogoPorProcesoRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://grupobancolombia.com/ents/SOI/MessageFormat/V2.1")]
        public AppFacadeWS.RecuperarCatalogoBB2.RequestHeader requestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://grupobancolombia.com/intf/ServiciosAdministrativos/ServiciosdeInformacionD" +
            "ocumental/RecuperarCatalogo_BB2/V1.0", Order=0)]
        public AppFacadeWS.RecuperarCatalogoBB2.RecuperarCatalogoPorProceso recuperarCatalogoPorProceso;
        
        public recuperarCatalogoPorProcesoRequest() {
        }
        
        public recuperarCatalogoPorProcesoRequest(AppFacadeWS.RecuperarCatalogoBB2.RequestHeader requestHeader, AppFacadeWS.RecuperarCatalogoBB2.RecuperarCatalogoPorProceso recuperarCatalogoPorProceso) {
            this.requestHeader = requestHeader;
            this.recuperarCatalogoPorProceso = recuperarCatalogoPorProceso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class recuperarCatalogoPorProcesoResponse1 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://grupobancolombia.com/ents/SOI/MessageFormat/V2.1")]
        public AppFacadeWS.RecuperarCatalogoBB2.ResponseHeader responseHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://grupobancolombia.com/intf/ServiciosAdministrativos/ServiciosdeInformacionD" +
            "ocumental/RecuperarCatalogo_BB2/V1.0", Order=0)]
        public AppFacadeWS.RecuperarCatalogoBB2.RecuperarCatalogoPorProcesoResponse recuperarCatalogoPorProcesoResponse;
        
        public recuperarCatalogoPorProcesoResponse1() {
        }
        
        public recuperarCatalogoPorProcesoResponse1(AppFacadeWS.RecuperarCatalogoBB2.ResponseHeader responseHeader, AppFacadeWS.RecuperarCatalogoBB2.RecuperarCatalogoPorProcesoResponse recuperarCatalogoPorProcesoResponse) {
            this.responseHeader = responseHeader;
            this.recuperarCatalogoPorProcesoResponse = recuperarCatalogoPorProcesoResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobancolombia.com/intf/ServiciosAdministrativos/ServiciosdeInformacionD" +
        "ocumental/RecuperarCatalogo_BB2/V1.0")]
    public partial class RecuperarCatalogoPorCliente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private clientRequest arg0Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public clientRequest arg0 {
            get {
                return this.arg0Field;
            }
            set {
                this.arg0Field = value;
                this.RaisePropertyChanged("arg0");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobancolombia.com/intf/ServiciosAdministrativos/ServiciosdeInformacionD" +
        "ocumental/RecuperarCatalogo_BB2/V1.0")]
    public partial class clientRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string documentIdTypeField;
        
        private string idNumberField;
        
        private string originField;
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string documentIdType {
            get {
                return this.documentIdTypeField;
            }
            set {
                this.documentIdTypeField = value;
                this.RaisePropertyChanged("documentIdType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string idNumber {
            get {
                return this.idNumberField;
            }
            set {
                this.idNumberField = value;
                this.RaisePropertyChanged("idNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string origin {
            get {
                return this.originField;
            }
            set {
                this.originField = value;
                this.RaisePropertyChanged("origin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("process", typeof(process), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("product", typeof(product), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobancolombia.com/intf/ServiciosAdministrativos/ServiciosdeInformacionD" +
        "ocumental/RecuperarCatalogo_BB2/V1.0")]
    public partial class process : object, System.ComponentModel.INotifyPropertyChanged {
        
        private attributes[] attributesField;
        
        private string branchCodeField;
        
        private string processCodeField;
        
        private string subProcessCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attributes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public attributes[] attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
                this.RaisePropertyChanged("attributes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string branchCode {
            get {
                return this.branchCodeField;
            }
            set {
                this.branchCodeField = value;
                this.RaisePropertyChanged("branchCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string processCode {
            get {
                return this.processCodeField;
            }
            set {
                this.processCodeField = value;
                this.RaisePropertyChanged("processCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string subProcessCode {
            get {
                return this.subProcessCodeField;
            }
            set {
                this.subProcessCodeField = value;
                this.RaisePropertyChanged("subProcessCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobancolombia.com/intf/ServiciosAdministrativos/ServiciosdeInformacionD" +
        "ocumental/RecuperarCatalogo_BB2/V1.0")]
    public partial class product : object, System.ComponentModel.INotifyPropertyChanged {
        
        private attributes[] attributesField;
        
        private string branchCodeField;
        
        private string productCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("attributes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public attributes[] attributes {
            get {
                return this.attributesField;
            }
            set {
                this.attributesField = value;
                this.RaisePropertyChanged("attributes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string branchCode {
            get {
                return this.branchCodeField;
            }
            set {
                this.branchCodeField = value;
                this.RaisePropertyChanged("branchCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string productCode {
            get {
                return this.productCodeField;
            }
            set {
                this.productCodeField = value;
                this.RaisePropertyChanged("productCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobancolombia.com/intf/ServiciosAdministrativos/ServiciosdeInformacionD" +
        "ocumental/RecuperarCatalogo_BB2/V1.0")]
    public partial class RecuperarCatalogoPorClienteResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private clientDocuments[] returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public clientDocuments[] @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobancolombia.com/intf/ServiciosAdministrativos/ServiciosdeInformacionD" +
        "ocumental/RecuperarCatalogo_BB2/V1.0")]
    public partial class clientDocuments : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string conditionFormField;
        
        private string documentStatusField;
        
        private string documentSubTypeField;
        
        private string documentTypeField;
        
        private string documentTypeNameField;
        
        private int expiryDaysField;
        
        private bool expiryDaysFieldSpecified;
        
        private System.DateTime expiryDateField;
        
        private bool expiryDateFieldSpecified;
        
        private string obligatoryField;
        
        private string urlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string conditionForm {
            get {
                return this.conditionFormField;
            }
            set {
                this.conditionFormField = value;
                this.RaisePropertyChanged("conditionForm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string documentStatus {
            get {
                return this.documentStatusField;
            }
            set {
                this.documentStatusField = value;
                this.RaisePropertyChanged("documentStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string documentSubType {
            get {
                return this.documentSubTypeField;
            }
            set {
                this.documentSubTypeField = value;
                this.RaisePropertyChanged("documentSubType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string documentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
                this.RaisePropertyChanged("documentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string documentTypeName {
            get {
                return this.documentTypeNameField;
            }
            set {
                this.documentTypeNameField = value;
                this.RaisePropertyChanged("documentTypeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int expiryDays {
            get {
                return this.expiryDaysField;
            }
            set {
                this.expiryDaysField = value;
                this.RaisePropertyChanged("expiryDays");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expiryDaysSpecified {
            get {
                return this.expiryDaysFieldSpecified;
            }
            set {
                this.expiryDaysFieldSpecified = value;
                this.RaisePropertyChanged("expiryDaysSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=6)]
        public System.DateTime expiryDate {
            get {
                return this.expiryDateField;
            }
            set {
                this.expiryDateField = value;
                this.RaisePropertyChanged("expiryDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expiryDateSpecified {
            get {
                return this.expiryDateFieldSpecified;
            }
            set {
                this.expiryDateFieldSpecified = value;
                this.RaisePropertyChanged("expiryDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string obligatory {
            get {
                return this.obligatoryField;
            }
            set {
                this.obligatoryField = value;
                this.RaisePropertyChanged("obligatory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("url");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class recuperarCatalogoPorClienteRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://grupobancolombia.com/ents/SOI/MessageFormat/V2.1")]
        public AppFacadeWS.RecuperarCatalogoBB2.RequestHeader requestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://grupobancolombia.com/intf/ServiciosAdministrativos/ServiciosdeInformacionD" +
            "ocumental/RecuperarCatalogo_BB2/V1.0", Order=0)]
        public AppFacadeWS.RecuperarCatalogoBB2.RecuperarCatalogoPorCliente recuperarCatalogoPorCliente;
        
        public recuperarCatalogoPorClienteRequest() {
        }
        
        public recuperarCatalogoPorClienteRequest(AppFacadeWS.RecuperarCatalogoBB2.RequestHeader requestHeader, AppFacadeWS.RecuperarCatalogoBB2.RecuperarCatalogoPorCliente recuperarCatalogoPorCliente) {
            this.requestHeader = requestHeader;
            this.recuperarCatalogoPorCliente = recuperarCatalogoPorCliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class recuperarCatalogoPorClienteResponse1 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://grupobancolombia.com/ents/SOI/MessageFormat/V2.1")]
        public AppFacadeWS.RecuperarCatalogoBB2.ResponseHeader responseHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://grupobancolombia.com/intf/ServiciosAdministrativos/ServiciosdeInformacionD" +
            "ocumental/RecuperarCatalogo_BB2/V1.0", Order=0)]
        public AppFacadeWS.RecuperarCatalogoBB2.RecuperarCatalogoPorClienteResponse recuperarCatalogoPorClienteResponse;
        
        public recuperarCatalogoPorClienteResponse1() {
        }
        
        public recuperarCatalogoPorClienteResponse1(AppFacadeWS.RecuperarCatalogoBB2.ResponseHeader responseHeader, AppFacadeWS.RecuperarCatalogoBB2.RecuperarCatalogoPorClienteResponse recuperarCatalogoPorClienteResponse) {
            this.responseHeader = responseHeader;
            this.recuperarCatalogoPorClienteResponse = recuperarCatalogoPorClienteResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RecuperarCatalogo_BB2Channel : AppFacadeWS.RecuperarCatalogoBB2.RecuperarCatalogo_BB2, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RecuperarCatalogo_BB2Client : System.ServiceModel.ClientBase<AppFacadeWS.RecuperarCatalogoBB2.RecuperarCatalogo_BB2>, AppFacadeWS.RecuperarCatalogoBB2.RecuperarCatalogo_BB2 {
        
        public RecuperarCatalogo_BB2Client() {
        }
        
        public RecuperarCatalogo_BB2Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RecuperarCatalogo_BB2Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecuperarCatalogo_BB2Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecuperarCatalogo_BB2Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppFacadeWS.RecuperarCatalogoBB2.recuperarCatalogoPorProductoResponse1 AppFacadeWS.RecuperarCatalogoBB2.RecuperarCatalogo_BB2.recuperarCatalogoPorProducto(AppFacadeWS.RecuperarCatalogoBB2.recuperarCatalogoPorProductoRequest request) {
            return base.Channel.recuperarCatalogoPorProducto(request);
        }
        
        public AppFacadeWS.RecuperarCatalogoBB2.ResponseHeader recuperarCatalogoPorProducto(AppFacadeWS.RecuperarCatalogoBB2.RequestHeader requestHeader, AppFacadeWS.RecuperarCatalogoBB2.RecuperarCatalogoPorProducto recuperarCatalogoPorProducto1, out AppFacadeWS.RecuperarCatalogoBB2.RecuperarCatalogoPorProductoResponse recuperarCatalogoPorProductoResponse) {
            AppFacadeWS.RecuperarCatalogoBB2.recuperarCatalogoPorProductoRequest inValue = new AppFacadeWS.RecuperarCatalogoBB2.recuperarCatalogoPorProductoRequest();
            inValue.requestHeader = requestHeader;
            inValue.recuperarCatalogoPorProducto = recuperarCatalogoPorProducto1;
            AppFacadeWS.RecuperarCatalogoBB2.recuperarCatalogoPorProductoResponse1 retVal = ((AppFacadeWS.RecuperarCatalogoBB2.RecuperarCatalogo_BB2)(this)).recuperarCatalogoPorProducto(inValue);
            recuperarCatalogoPorProductoResponse = retVal.recuperarCatalogoPorProductoResponse;
            return retVal.responseHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppFacadeWS.RecuperarCatalogoBB2.recuperarCatalogoPorProcesoResponse1 AppFacadeWS.RecuperarCatalogoBB2.RecuperarCatalogo_BB2.recuperarCatalogoPorProceso(AppFacadeWS.RecuperarCatalogoBB2.recuperarCatalogoPorProcesoRequest request) {
            return base.Channel.recuperarCatalogoPorProceso(request);
        }
        
        public AppFacadeWS.RecuperarCatalogoBB2.ResponseHeader recuperarCatalogoPorProceso(AppFacadeWS.RecuperarCatalogoBB2.RequestHeader requestHeader, AppFacadeWS.RecuperarCatalogoBB2.RecuperarCatalogoPorProceso recuperarCatalogoPorProceso1, out AppFacadeWS.RecuperarCatalogoBB2.RecuperarCatalogoPorProcesoResponse recuperarCatalogoPorProcesoResponse) {
            AppFacadeWS.RecuperarCatalogoBB2.recuperarCatalogoPorProcesoRequest inValue = new AppFacadeWS.RecuperarCatalogoBB2.recuperarCatalogoPorProcesoRequest();
            inValue.requestHeader = requestHeader;
            inValue.recuperarCatalogoPorProceso = recuperarCatalogoPorProceso1;
            AppFacadeWS.RecuperarCatalogoBB2.recuperarCatalogoPorProcesoResponse1 retVal = ((AppFacadeWS.RecuperarCatalogoBB2.RecuperarCatalogo_BB2)(this)).recuperarCatalogoPorProceso(inValue);
            recuperarCatalogoPorProcesoResponse = retVal.recuperarCatalogoPorProcesoResponse;
            return retVal.responseHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppFacadeWS.RecuperarCatalogoBB2.recuperarCatalogoPorClienteResponse1 AppFacadeWS.RecuperarCatalogoBB2.RecuperarCatalogo_BB2.recuperarCatalogoPorCliente(AppFacadeWS.RecuperarCatalogoBB2.recuperarCatalogoPorClienteRequest request) {
            return base.Channel.recuperarCatalogoPorCliente(request);
        }
        
        public AppFacadeWS.RecuperarCatalogoBB2.ResponseHeader recuperarCatalogoPorCliente(AppFacadeWS.RecuperarCatalogoBB2.RequestHeader requestHeader, AppFacadeWS.RecuperarCatalogoBB2.RecuperarCatalogoPorCliente recuperarCatalogoPorCliente1, out AppFacadeWS.RecuperarCatalogoBB2.RecuperarCatalogoPorClienteResponse recuperarCatalogoPorClienteResponse) {
            AppFacadeWS.RecuperarCatalogoBB2.recuperarCatalogoPorClienteRequest inValue = new AppFacadeWS.RecuperarCatalogoBB2.recuperarCatalogoPorClienteRequest();
            inValue.requestHeader = requestHeader;
            inValue.recuperarCatalogoPorCliente = recuperarCatalogoPorCliente1;
            AppFacadeWS.RecuperarCatalogoBB2.recuperarCatalogoPorClienteResponse1 retVal = ((AppFacadeWS.RecuperarCatalogoBB2.RecuperarCatalogo_BB2)(this)).recuperarCatalogoPorCliente(inValue);
            recuperarCatalogoPorClienteResponse = retVal.recuperarCatalogoPorClienteResponse;
            return retVal.responseHeader;
        }
    }
}
