//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppFacadeWS.ConsultarListasControl {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobancolombia.com/ents/common/GenericException/V2.0")]
    public partial class GenericException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobancolombia.com/ents/CumplimientoYRegulatoria/OtrasRegulaciones/Estad" +
        "oClienteListasControl/V1.0")]
    public partial class EstadoClienteListasControl : object, System.ComponentModel.INotifyPropertyChanged {
        
        private IdentificacionCliente identidadClienteField;
        
        private string tipoEstadoField;
        
        private string mensajeEstadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public IdentificacionCliente identidadCliente {
            get {
                return this.identidadClienteField;
            }
            set {
                this.identidadClienteField = value;
                this.RaisePropertyChanged("identidadCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string tipoEstado {
            get {
                return this.tipoEstadoField;
            }
            set {
                this.tipoEstadoField = value;
                this.RaisePropertyChanged("tipoEstado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string mensajeEstado {
            get {
                return this.mensajeEstadoField;
            }
            set {
                this.mensajeEstadoField = value;
                this.RaisePropertyChanged("mensajeEstado");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobancolombia.com/ents/Participante/Demografica/CRM/IdentificacionClien" +
        "te/V1.0")]
    public partial class IdentificacionCliente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tipoDocumentoField;
        
        private string numeroDocumentoField;
        
        private string nombreCompletoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
                this.RaisePropertyChanged("tipoDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string numeroDocumento {
            get {
                return this.numeroDocumentoField;
            }
            set {
                this.numeroDocumentoField = value;
                this.RaisePropertyChanged("numeroDocumento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombreCompleto {
            get {
                return this.nombreCompletoField;
            }
            set {
                this.nombreCompletoField = value;
                this.RaisePropertyChanged("nombreCompleto");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobancolombia.com/intf/ServiciosApoyo/PrevencionLavadoActivos/Consultar" +
        "EstadoClienteListasControl/V1.0")]
    public partial class ConsultarEstadoClienteListasControlResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private EstadoClienteListasControl estadoClienteListasControlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public EstadoClienteListasControl estadoClienteListasControl {
            get {
                return this.estadoClienteListasControlField;
            }
            set {
                this.estadoClienteListasControlField = value;
                this.RaisePropertyChanged("estadoClienteListasControl");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobancolombia.com/intf/ServiciosApoyo/PrevencionLavadoActivos/Consultar" +
        "EstadoClienteListasControl/V1.0")]
    public partial class ConsultarEstadoClienteListasControl : object, System.ComponentModel.INotifyPropertyChanged {
        
        private IdentificacionCliente identidadClienteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public IdentificacionCliente identidadCliente {
            get {
                return this.identidadClienteField;
            }
            set {
                this.identidadClienteField = value;
                this.RaisePropertyChanged("identidadCliente");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="ConsultarEstadoClienteListasControl", Namespace="http://grupobancolombia.com/intf/ServiciosApoyo/PrevencionLavadoActivos/Consultar" +
        "EstadoClienteListasControl/V1.0", ConfigurationName="ConsultarListasControl.ConsultarEstadoClienteListasControl1")]
    public interface ConsultarEstadoClienteListasControl1 {
        
        // CODEGEN: Generating message contract since the operation consultarEstadoClienteListasControl is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://grupobancolombia.com/intf/ServiciosApoyo/PrevencionLavadoActivos/Consultar" +
            "EstadoClienteListasControl/V1.0/consultarEstadoClienteListasControl", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AppFacadeWS.ConsultarListasControl.GenericException), Action="http://grupobancolombia.com/intf/ServiciosApoyo/PrevencionLavadoActivos/Consultar" +
            "EstadoClienteListasControl/V1.0/consultarEstadoClienteListasControl", Name="businessException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AppFacadeWS.ConsultarListasControl.consultarEstadoClienteListasControlResponse1 consultarEstadoClienteListasControl(AppFacadeWS.ConsultarListasControl.consultarEstadoClienteListasControlRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobancolombia.com/ents/SOI/MessageFormat/V2.1")]
    public partial class RequestHeader : Header {
        
        private UsernameToken userIdField;
        
        private Destination destinationField;
        
        private string[] classificationsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public UsernameToken userId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("userId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public Destination destination {
            get {
                return this.destinationField;
            }
            set {
                this.destinationField = value;
                this.RaisePropertyChanged("destination");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("classification", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI", IsNullable=false)]
        public string[] classifications {
            get {
                return this.classificationsField;
            }
            set {
                this.classificationsField = value;
                this.RaisePropertyChanged("classifications");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobancolombia.com/ents/SOI/CoreExtensions/V2.1")]
    public partial class UsernameToken : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private object userTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("userName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public object userToken {
            get {
                return this.userTokenField;
            }
            set {
                this.userTokenField = value;
                this.RaisePropertyChanged("userToken");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobancolombia.com/ents/SOI/CoreExtensions/V2.1")]
    public partial class Destination : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string namespaceField;
        
        private string operationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI", Order=1)]
        public string @namespace {
            get {
                return this.namespaceField;
            }
            set {
                this.namespaceField = value;
                this.RaisePropertyChanged("namespace");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
                this.RaisePropertyChanged("operation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResponseHeader))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RequestHeader))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobancolombia.com/ents/SOI/MessageFormat/V2.1")]
    public abstract partial class Header : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string systemIdField;
        
        private string messageIdField;
        
        private System.DateTime timestampField;
        
        private bool timestampFieldSpecified;
        
        private Property[] messageContextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string systemId {
            get {
                return this.systemIdField;
            }
            set {
                this.systemIdField = value;
                this.RaisePropertyChanged("systemId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string messageId {
            get {
                return this.messageIdField;
            }
            set {
                this.messageIdField = value;
                this.RaisePropertyChanged("messageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime timestamp {
            get {
                return this.timestampField;
            }
            set {
                this.timestampField = value;
                this.RaisePropertyChanged("timestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timestampSpecified {
            get {
                return this.timestampFieldSpecified;
            }
            set {
                this.timestampFieldSpecified = value;
                this.RaisePropertyChanged("timestampSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("property", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public Property[] messageContext {
            get {
                return this.messageContextField;
            }
            set {
                this.messageContextField = value;
                this.RaisePropertyChanged("messageContext");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobancolombia.com/ents/SOI/CoreExtensions/V2.1")]
    public partial class Property : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobancolombia.com/ents/SOI/MessageFormat/V2.1")]
    public partial class ResponseHeader : Header {
        
        private ResponseStatus responseStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public ResponseStatus responseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
                this.RaisePropertyChanged("responseStatus");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobancolombia.com/ents/SOI/CoreExtensions/V2.1")]
    public partial class ResponseStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private StatusCode statusCodeField;
        
        public ResponseStatus() {
            this.statusCodeField = StatusCode.Success;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public StatusCode statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("statusCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupobancolombia.com/ents/SOI/CoreExtensions/V2.1")]
    public enum StatusCode {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        BusinessException,
        
        /// <remarks/>
        ProviderException,
        
        /// <remarks/>
        SystemException,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarEstadoClienteListasControlRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://grupobancolombia.com/ents/SOI/MessageFormat/V2.1")]
        public AppFacadeWS.ConsultarListasControl.RequestHeader requestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://grupobancolombia.com/intf/ServiciosApoyo/PrevencionLavadoActivos/Consultar" +
            "EstadoClienteListasControl/V1.0", Order=0)]
        public AppFacadeWS.ConsultarListasControl.ConsultarEstadoClienteListasControl consultarEstadoClienteListasControl;
        
        public consultarEstadoClienteListasControlRequest() {
        }
        
        public consultarEstadoClienteListasControlRequest(AppFacadeWS.ConsultarListasControl.RequestHeader requestHeader, AppFacadeWS.ConsultarListasControl.ConsultarEstadoClienteListasControl consultarEstadoClienteListasControl) {
            this.requestHeader = requestHeader;
            this.consultarEstadoClienteListasControl = consultarEstadoClienteListasControl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarEstadoClienteListasControlResponse1 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://grupobancolombia.com/ents/SOI/MessageFormat/V2.1")]
        public AppFacadeWS.ConsultarListasControl.ResponseHeader responseHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://grupobancolombia.com/intf/ServiciosApoyo/PrevencionLavadoActivos/Consultar" +
            "EstadoClienteListasControl/V1.0", Order=0)]
        public AppFacadeWS.ConsultarListasControl.ConsultarEstadoClienteListasControlResponse consultarEstadoClienteListasControlResponse;
        
        public consultarEstadoClienteListasControlResponse1() {
        }
        
        public consultarEstadoClienteListasControlResponse1(AppFacadeWS.ConsultarListasControl.ResponseHeader responseHeader, AppFacadeWS.ConsultarListasControl.ConsultarEstadoClienteListasControlResponse consultarEstadoClienteListasControlResponse) {
            this.responseHeader = responseHeader;
            this.consultarEstadoClienteListasControlResponse = consultarEstadoClienteListasControlResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConsultarEstadoClienteListasControl1Channel : AppFacadeWS.ConsultarListasControl.ConsultarEstadoClienteListasControl1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultarEstadoClienteListasControl1Client : System.ServiceModel.ClientBase<AppFacadeWS.ConsultarListasControl.ConsultarEstadoClienteListasControl1>, AppFacadeWS.ConsultarListasControl.ConsultarEstadoClienteListasControl1 {
        
        public ConsultarEstadoClienteListasControl1Client() {
        }
        
        public ConsultarEstadoClienteListasControl1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultarEstadoClienteListasControl1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultarEstadoClienteListasControl1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultarEstadoClienteListasControl1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppFacadeWS.ConsultarListasControl.consultarEstadoClienteListasControlResponse1 AppFacadeWS.ConsultarListasControl.ConsultarEstadoClienteListasControl1.consultarEstadoClienteListasControl(AppFacadeWS.ConsultarListasControl.consultarEstadoClienteListasControlRequest request) {
            return base.Channel.consultarEstadoClienteListasControl(request);
        }
        
        public AppFacadeWS.ConsultarListasControl.ResponseHeader consultarEstadoClienteListasControl(AppFacadeWS.ConsultarListasControl.RequestHeader requestHeader, AppFacadeWS.ConsultarListasControl.ConsultarEstadoClienteListasControl consultarEstadoClienteListasControl1, out AppFacadeWS.ConsultarListasControl.ConsultarEstadoClienteListasControlResponse consultarEstadoClienteListasControlResponse) {
            AppFacadeWS.ConsultarListasControl.consultarEstadoClienteListasControlRequest inValue = new AppFacadeWS.ConsultarListasControl.consultarEstadoClienteListasControlRequest();
            inValue.requestHeader = requestHeader;
            inValue.consultarEstadoClienteListasControl = consultarEstadoClienteListasControl1;
            AppFacadeWS.ConsultarListasControl.consultarEstadoClienteListasControlResponse1 retVal = ((AppFacadeWS.ConsultarListasControl.ConsultarEstadoClienteListasControl1)(this)).consultarEstadoClienteListasControl(inValue);
            consultarEstadoClienteListasControlResponse = retVal.consultarEstadoClienteListasControlResponse;
            return retVal.responseHeader;
        }
    }
}
